package com.demo.entities;
// Generated Oct 30, 2023, 9:37:28 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;


/**
 * Douutien generated by hbm2java
 */
@Entity
@Table(name = "douutien" )
public class Douutien implements java.io.Serializable {

	private Integer madouutien;
	
	private String tendouutien;
	
	private Set<Yeucau> yeucaus = new HashSet<Yeucau>(0);

	public Douutien() {
	}

	public Douutien(String tendouutien) {
		this.tendouutien = tendouutien;
	}

	public Douutien(String tendouutien, Set<Yeucau> yeucaus) {
		this.tendouutien = tendouutien;
		this.yeucaus = yeucaus;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "madouutien", unique = true, nullable = false)
	public Integer getMadouutien() {
		return this.madouutien;
	}

	public void setMadouutien(Integer madouutien) {
		this.madouutien = madouutien;
	}

	@Column(name = "tendouutien", nullable = false, length = 250)
	public String getTendouutien() {
		return this.tendouutien;
	}

	public void setTendouutien(String tendouutien) {
		this.tendouutien = tendouutien;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "douutien")
	public Set<Yeucau> getYeucaus() {
		return this.yeucaus;
	}

	public void setYeucaus(Set<Yeucau> yeucaus) {
		this.yeucaus = yeucaus;
	}

}
